apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: org1-f-1
  name: admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
       app: hyperledger
       role: admin
       org: org1-f-1
       name: admin
    spec:
      # nodeSelector:
      #   # assume all org node can access to docker
      #   org: org1-f-1
      containers:
       - name: admin
         image: hyperledger/admin-api
         imagePullPolicy: Never
         env: 
         - name:  PORT
           value: "9000"
         ports:
          - containerPort: 9000
         # command: ["yarn", "yarn start"]
         command: [ "/bin/bash", "-c", "--" ]
         args: [ "yarn && yarn start" ]
         # args: [ "while true; do sleep 30; done;" ]                    
         workingDir: /home
         volumeMounts:
          - mountPath: /host/var/run/
            name: run
          - mountPath: /home
            name: working

      restartPolicy: Always

      volumes:
         - name: run
           hostPath:
             path: /var/run
         - name: working
           hostPath:
             path: /Users/thanhtu/MyProjects/Hyperledger/Fabric/baas/admin

--- 
apiVersion: v1
kind: Service
metadata:
   namespace: org1-f-1
   name: admin
spec:
 selector:
   app: hyperledger
   role: admin
   org: org1-f-1
   name: admin
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 9000     
     targetPort: 9000
     nodePort: 30900

