# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

volumes:
  orderer_healthcare_com:
  peer0_hprovider_healthcare_com:    

networks:
  health_network:
    external: 
      name: health_network

services:

  orderer_healthcare_com:
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    hostname: orderer.healthcare.com
    env_file: env/.orderer-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/healthcare.com/orderers/orderer.healthcare.com/tls/:/var/hyperledger/orderer/tls
        - orderer_healthcare_com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      health_network:
        aliases:
          - orderer.healthcare.com

  
  peer0_hprovider_healthcare_com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: peer0.hprovider.healthcare.com
    env_file: env/.peer1-hp-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer0.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer0_hprovider_healthcare_com:/var/hyperledger/production
    ports:
      - 7051:7051
    networks:
      health_network:
        aliases:
          - peer0_hprovider_healthcare_com
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
    


  cli:
    hostname: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    env_file: env/.cli-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer_healthcare_com
      - peer0_hprovider_healthcare_com
    deploy:
      replicas: 5
      placement:
        constraints: [node.role == worker]
    networks:
      health_network:
        aliases:
          - cli
    
