# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

networks:
  health_network:
    external: 
      name: health_network
  

services:
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      health_network:
        aliases:
          - couchdb0
    deploy:
      placement:
        constraints: [node.role == manager]

  peer0_hprovider_healthcare_com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=erikson
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=wines
    depends_on:
      - couchdb0