# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

networks:
  health_network:
    external:
      name: health_network

services:
  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:letast
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      health_network:
        aliases:
          - couchdb3
    deploy:
      placement:
        constraints: [node.role == manager]

  couchdb5:
    container_name: couchdb5
    image: hyperledger/fabric-couchdb:letast
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "8984:5984"
    networks:
      health_network:
        aliases:
          - couchdb5
    deploy:
      placement:
        constraints: [node.role == manager]