# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

volumes:
  peer1.hprovider.healthcare.com:
  peer2.hprovider.healthcare.com:  
  peer3.hprovider.healthcare.com:
  peer4.hprovider.healthcare.com:

networks:
  health_network:
    external: 
      name: health_network

services:

  peer1_hprovider_healthcare_com:
    container_name: peer1.hprovider.healthcare.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: peer1.hprovider.healthcare.com
    env_file: env/.peer1-hp-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer1.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hprovider.healthcare.com:/var/hyperledger/production
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == worker]
    ports:
      - 8051:8051
    networks:
      health_network:
        aliases:
          - peer1.hprovider.healthcare.com
  
  
  peer2_hprovider_healthcare_com:
    container_name: peer2.hprovider.healthcare.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    hostname: peer2.hprovider.healthcare.com
    env_file: env/.peer2-hp-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer2.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer2.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer2.hprovider.healthcare.com:/var/hyperledger/production
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == worker]
    ports:
      - 11051:8051
    networks:
      health_network:
        aliases:
          - peer2.hprovider.healthcare.com
    

  peer3_hprovider_healthcare_com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    container_name: peer3.hprovider.healthcare.com
    hostname: peer3.hprovider.healthcare.com
    env_file: env/.peer3-hp-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer3.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer3.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer3.hprovider.healthcare.com:/var/hyperledger/production
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == worker]
    ports:
      - 12051:8051
    networks:
      health_network:
        aliases:
          - peer3.hprovider.healthcare.com
    
  
  peer4_hprovider_healthcare_com:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    container_name: peer4.hprovider.healthcare.com
    hostname: peer4.hprovider.healthcare.com
    env_file: env/.peer4-hp-env
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer4.hprovider.healthcare.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/hprovider.healthcare.com/peers/peer4.hprovider.healthcare.com/tls:/etc/hyperledger/fabric/tls
        - peer4.hprovider.healthcare.com:/var/hyperledger/production
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == worker]
    ports:
      - 13051:8051
    networks:
      health_network:
        aliases:
          - peer4.hprovider.healthcare.com
    

  # cli_pc2:
  #   #hostname: clipc2
  #   image: hyperledger/fabric-tools:$IMAGE_TAG
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     - SYS_CHANNEL=$SYS_CHANNEL
  #     - GOPATH=/opt/gopath
  #     - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
  #     #- FABRIC_LOGGING_SPEC=DEBUG
  #     - FABRIC_LOGGING_SPEC=INFO
  #     - CORE_PEER_ID=cli_pc2
  #     - CORE_PEER_ADDRESS=peer0.hprovider_healthcare_com:7051
  #     - CORE_PEER_LOCALMSPID=HProviderMSP
  #     - CORE_PEER_TLS_ENABLED=true
  #     - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hprovider_healthcare_com/peers/peer0.hprovider_healthcare_com/tls/server.crt
  #     - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hprovider_healthcare_com/peers/peer0.hprovider_healthcare_com/tls/server.key
  #     - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hprovider_healthcare_com/peers/peer0.hprovider_healthcare_com/tls/ca.crt
  #     - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hprovider_healthcare_com/users/Admin@hprovider_healthcare_com/msp
  #   working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
  #   command: /bin/bash
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ./chaincode/:/opt/gopath/src/github.com/chaincode
  #       - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
  #       - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
  #       - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
  #   depends_on:
  #     - peer1_hprovider_healthcare_com
  #     - peer2_hprovider_ healthcare_com
  #     - peer3_hprovider_healthcare_com
  #     - peer4_hprovider_healthcare_com
  #   networks:
  #     health_network:
  #       aliases:
  #         - cli_pc2

  
