# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  health_network:

services:
  couchdb7:
    container_name: couchdb7
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "12984:5984"
    networks:
      - health_network

  peer2.research.healthcare.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb7:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=erikson
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=wines
    depends_on:
      - couchdb7
  
  couchdb8:
    container_name: couchdb8
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "13984:5984"
    networks:
      - health_network

  peer3.research.healthcare.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb8:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=erikson
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=wines
    depends_on:
      - couchdb8

  couchdb9:
    container_name: couchdb9
    image: hyperledger/fabric-couchdb
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "14984:5984"
    networks:
      - health_network

  peer4.research.healthcare.com:
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb9:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=erikson
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=wines
    depends_on:
      - couchdb9