# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3'

networks:
  health_network:
    external: 
      name: health_network

services:
  couchdb1:
    hostname: couchdb1
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    deploy:
      placement:
        constraints: [node.role == worker]
    ports:
      - "6984:5984"
    networks:
      health_network:
        aliases:
          - couchdb1
    


  couchdb4:
    hostname: couchdb4
    container_name: couchdb4
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    deploy:
      placement:
        constraints: [node.role == worker]
    ports:
      - "9984:5984"
    networks:
      health_network:
        aliases:
          - couchdb4
    
  
  couchdb5:
    hostname: couchdb5
    container_name: couchdb5
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    deploy:
      placement:
        constraints: [node.role == worker]
    ports:
      - "10984:5984"
    networks:
      health_network:
        aliases:
          - couchdb5
    

 
  couchdb6:
    hostname: couchdb6
    container_name: couchdb6
    image: hyperledger/fabric-couchdb:latest
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=erikson
      - COUCHDB_PASSWORD=wines
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for healthcare map it to utilize Fauxton User Interface in dev environments.
    deploy:
      mode: replicated
      placement:
        constraints: [node.role == worker]
    ports:
      - "11984:5984"
    networks:
      health_network:
        aliases:
          - couchdb6
    