Profiles:
  TwoOrgsChannel:
    Consortium: HealthConsortium
    Application:
      Organizations:
      - Name: HProviderMSP
        ID: HProviderMSP
        MSPDir: crypto-config/peerOrganizations/hprovider.healthcare.com/msp
        AnchorPeers:
        - Host: peer0.hprovider.healthcare.com
          Port: 7051
      - Name: ResearchMSP
        ID: ResearchMSP
        MSPDir: crypto-config/peerOrganizations/research.healthcare.com/msp
        AnchorPeers:
        - Host: peer0.research.healthcare.com
          Port: 7051
  TwoOrgsOrdererGenesis:
    Orderer:
      OrdererType: kafka
      Addresses:
      - orderer0.healthcare.com:7050
      - orderer1.healthcare.com:7050
      - orderer2.healthcare.com:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 103809024
        PreferredMaxBytes: 524288
      Kafka:
        Brokers:
        - kafka0.healthcare.com:9092
        - kafka1.healthcare.com:9092
        - kafka2.healthcare.com:9092
      Organizations:
      - Name: OrdererOrg
        ID: OrdererMSP
        MSPDir: crypto-config/ordererOrganizations/healthcare.com/msp
    Consortiums:
      HealthConsortium:
        Organizations:
        - Name: HProviderMSP
          ID: HProviderMSP
          MSPDir: crypto-config/peerOrganizations/hprovider.healthcare.com/msp
          AnchorPeers:
          - Host: peer0.hprovider.healthcare.com
            Port: 7051
        - Name: ResearchMSP
          ID: ResearchMSP
          MSPDir: crypto-config/peerOrganizations/research.healthcare.com/msp
          AnchorPeers:
          - Host: peer0.research.healthcare.com
            Port: 7051
Organizations:
- Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: crypto-config/ordererOrganizations/healthcare.com/msp
- Name: HProviderMSP
  ID: HProviderMSP
  MSPDir: crypto-config/peerOrganizations/hprovider.healthcare.com/msp
  AnchorPeers:
  - Host: peer0.hprovider.healthcare.com
    Port: 7051
- Name: ResearchMSP
  ID: ResearchMSP
  MSPDir: crypto-config/peerOrganizations/research.healthcare.com/msp
  AnchorPeers:
  - Host: peer0.research.healthcare.com
    Port: 7051
Orderer:
  OrdererType: kafka
  Addresses:
  - orderer0.healthcare.com:7050
  - orderer1.healthcare.com:7050
  - orderer2.healthcare.com:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 103809024
    PreferredMaxBytes: 524288
  Kafka:
    Brokers:
    - kafka0.healthcare.com:9092
    - kafka1.healthcare.com:9092
    - kafka2.healthcare.com:9092
  Organizations:
  - Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/healthcare.com/msp
