OrdererOrgs:
- Name: Orderer
  Domain: healthcare.com
  Specs:
  - Hostname: orderer0
  - Hostname: orderer1
  - Hostname: orderer2
PeerOrgs:
- Name: HProvider
  Domain: hprovider.healthcare.com
  Template:
    Count: 1
  Users:
    Count: 1
- Name: Research
  Domain: research.healthcare.com
  Template:
    Count: 1
  Users:
    Count: 1
