version: "3"
networks:
  health-network:
    external:
      name: health-network
services:
  zookeeper0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: zookeeper0
    image: hyperledger/fabric-zookeeper:x86_64-1.0.2
    networks:
      health-network:
        aliases:
        - zookeeper0.healthcare.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=health-network
    - ZOO_MY_ID=1
    - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
  zookeeper1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: zookeeper1
    image: hyperledger/fabric-zookeeper:x86_64-1.0.2
    networks:
      health-network:
        aliases:
        - zookeeper1.healthcare.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=health-network
    - ZOO_MY_ID=2
    - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
  zookeeper2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: zookeeper2
    image: hyperledger/fabric-zookeeper:x86_64-1.0.2
    networks:
      health-network:
        aliases:
        - zookeeper2.healthcare.com
    environment:
    - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=health-network
    - ZOO_MY_ID=3
    - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
