version: '3'

networks:
  health-network:
    # If network is created with deplyment, Chaincode container cannot connect to network
    # as the created network name is '<STACK NAME>_health-network'.
    # But chaincode container will attempt to connect 'health-network' network
    external:
      name: health-network

services:
  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: hyperledger/fabric-couchdb:x86_64-1.0.0-beta
    networks:
      - health-network

  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: hyperledger/fabric-couchdb:x86_64-1.0.0-beta
    networks:
      - health-network

  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: hyperledger/fabric-couchdb:x86_64-1.0.0-beta
    networks:
      - health-network

  couchdb3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    image: hyperledger/fabric-couchdb:x86_64-1.0.0-beta
    networks:
      - health-network
